version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
