version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - ./backend:/app
    restart: always
